// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Resolvers
{
    public class GeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;

        static GeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(18)
            {
                { typeof(global::Positron.Client.DataTransferObjects.RoomsListElement[]), 0 },
                { typeof(global::Positron.Client.GameEntities.NetGameObject[]), 1 },
                { typeof(global::Positron.Client.GameEntities.NetTransform[]), 2 },
                { typeof(global::Positron.Client.GameEntities.NetValue[]), 3 },
                { typeof(global::Positron.Client.GameEntities.RpcCall[]), 4 },
                { typeof(global::Positron.Client.DataTransferObjects.CreateRoomPacket), 5 },
                { typeof(global::Positron.Client.DataTransferObjects.GameTickPacket), 6 },
                { typeof(global::Positron.Client.DataTransferObjects.GameUnreliableTick), 7 },
                { typeof(global::Positron.Client.DataTransferObjects.JoinRoomRequest), 8 },
                { typeof(global::Positron.Client.DataTransferObjects.JoinRoomResponse), 9 },
                { typeof(global::Positron.Client.DataTransferObjects.RoomCreationResponse), 10 },
                { typeof(global::Positron.Client.DataTransferObjects.RoomListResponse), 11 },
                { typeof(global::Positron.Client.DataTransferObjects.RoomsListElement), 12 },
                { typeof(global::Positron.Client.GameEntities.NetGameObject), 13 },
                { typeof(global::Positron.Client.GameEntities.NetTransform), 14 },
                { typeof(global::Positron.Client.GameEntities.NetValue), 15 },
                { typeof(global::Positron.Client.GameEntities.Premitive.NetVector3), 16 },
                { typeof(global::Positron.Client.GameEntities.RpcCall), 17 },
            };
        }

        internal static object GetFormatter(global::System.Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new global::MessagePack.Formatters.ArrayFormatter<global::Positron.Client.DataTransferObjects.RoomsListElement>();
                case 1: return new global::MessagePack.Formatters.ArrayFormatter<global::Positron.Client.GameEntities.NetGameObject>();
                case 2: return new global::MessagePack.Formatters.ArrayFormatter<global::Positron.Client.GameEntities.NetTransform>();
                case 3: return new global::MessagePack.Formatters.ArrayFormatter<global::Positron.Client.GameEntities.NetValue>();
                case 4: return new global::MessagePack.Formatters.ArrayFormatter<global::Positron.Client.GameEntities.RpcCall>();
                case 5: return new MessagePack.Formatters.Positron.Client.DataTransferObjects.CreateRoomPacketFormatter();
                case 6: return new MessagePack.Formatters.Positron.Client.DataTransferObjects.GameTickPacketFormatter();
                case 7: return new MessagePack.Formatters.Positron.Client.DataTransferObjects.GameUnreliableTickFormatter();
                case 8: return new MessagePack.Formatters.Positron.Client.DataTransferObjects.JoinRoomRequestFormatter();
                case 9: return new MessagePack.Formatters.Positron.Client.DataTransferObjects.JoinRoomResponseFormatter();
                case 10: return new MessagePack.Formatters.Positron.Client.DataTransferObjects.RoomCreationResponseFormatter();
                case 11: return new MessagePack.Formatters.Positron.Client.DataTransferObjects.RoomListResponseFormatter();
                case 12: return new MessagePack.Formatters.Positron.Client.DataTransferObjects.RoomsListElementFormatter();
                case 13: return new MessagePack.Formatters.Positron.Client.GameEntities.NetGameObjectFormatter();
                case 14: return new MessagePack.Formatters.Positron.Client.GameEntities.NetTransformFormatter();
                case 15: return new MessagePack.Formatters.Positron.Client.GameEntities.NetValueFormatter();
                case 16: return new MessagePack.Formatters.Positron.Client.GameEntities.Premitive.NetVector3Formatter();
                case 17: return new MessagePack.Formatters.Positron.Client.GameEntities.RpcCallFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1649 // File name should match first type name




// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Positron.Client.DataTransferObjects
{
    public sealed class CreateRoomPacketFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Positron.Client.DataTransferObjects.CreateRoomPacket>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Positron.Client.DataTransferObjects.CreateRoomPacket value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(2);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Name, options);
            writer.Write(value.PlayerCap);
        }

        public global::Positron.Client.DataTransferObjects.CreateRoomPacket Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Positron.Client.DataTransferObjects.CreateRoomPacket();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Name = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        ____result.PlayerCap = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class GameTickPacketFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Positron.Client.DataTransferObjects.GameTickPacket>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Positron.Client.DataTransferObjects.GameTickPacket value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(7);
            writer.Write(value.Host);
            writer.Write(value.Client);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.NetGameObject[]>(formatterResolver).Serialize(ref writer, value.NewGameObjects, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<uint[]>(formatterResolver).Serialize(ref writer, value.RemovedObjects, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<uint[]>(formatterResolver).Serialize(ref writer, value.TransferedToHostObjects, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.NetValue[]>(formatterResolver).Serialize(ref writer, value.ValueModification, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.RpcCall[]>(formatterResolver).Serialize(ref writer, value.Rpcs, options);
        }

        public global::Positron.Client.DataTransferObjects.GameTickPacket Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Positron.Client.DataTransferObjects.GameTickPacket();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Host = reader.ReadUInt32();
                        break;
                    case 1:
                        ____result.Client = reader.ReadUInt32();
                        break;
                    case 2:
                        ____result.NewGameObjects = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.NetGameObject[]>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.RemovedObjects = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<uint[]>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        ____result.TransferedToHostObjects = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<uint[]>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 5:
                        ____result.ValueModification = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.NetValue[]>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 6:
                        ____result.Rpcs = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.RpcCall[]>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class GameUnreliableTickFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Positron.Client.DataTransferObjects.GameUnreliableTick>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Positron.Client.DataTransferObjects.GameUnreliableTick value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(3);
            writer.Write(value.TimeStamp);
            writer.Write(value.ClientId);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.NetTransform[]>(formatterResolver).Serialize(ref writer, value.MovedObjects, options);
        }

        public global::Positron.Client.DataTransferObjects.GameUnreliableTick Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Positron.Client.DataTransferObjects.GameUnreliableTick();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.TimeStamp = reader.ReadUInt64();
                        break;
                    case 1:
                        ____result.ClientId = reader.ReadUInt32();
                        break;
                    case 2:
                        ____result.MovedObjects = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.NetTransform[]>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class JoinRoomRequestFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Positron.Client.DataTransferObjects.JoinRoomRequest>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Positron.Client.DataTransferObjects.JoinRoomRequest value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(1);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Uuid, options);
        }

        public global::Positron.Client.DataTransferObjects.JoinRoomRequest Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Positron.Client.DataTransferObjects.JoinRoomRequest();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Uuid = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class JoinRoomResponseFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Positron.Client.DataTransferObjects.JoinRoomResponse>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Positron.Client.DataTransferObjects.JoinRoomResponse value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(6);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.NetGameObject[]>(formatterResolver).Serialize(ref writer, value.GameObjects, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.NetValue[]>(formatterResolver).Serialize(ref writer, value.Values, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.RpcCall[]>(formatterResolver).Serialize(ref writer, value.CachedRpcCalls, options);
            writer.Write(value.Tickrate);
            writer.Write(value.SelfId);
            writer.Write(value.Host);
        }

        public global::Positron.Client.DataTransferObjects.JoinRoomResponse Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Positron.Client.DataTransferObjects.JoinRoomResponse();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.GameObjects = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.NetGameObject[]>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        ____result.Values = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.NetValue[]>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.CachedRpcCalls = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.RpcCall[]>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 3:
                        ____result.Tickrate = reader.ReadUInt32();
                        break;
                    case 4:
                        ____result.SelfId = reader.ReadUInt32();
                        break;
                    case 5:
                        ____result.Host = reader.ReadUInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class RoomCreationResponseFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Positron.Client.DataTransferObjects.RoomCreationResponse>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Positron.Client.DataTransferObjects.RoomCreationResponse value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(1);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Uuid, options);
        }

        public global::Positron.Client.DataTransferObjects.RoomCreationResponse Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Positron.Client.DataTransferObjects.RoomCreationResponse();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Uuid = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class RoomListResponseFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Positron.Client.DataTransferObjects.RoomListResponse>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Positron.Client.DataTransferObjects.RoomListResponse value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(1);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.DataTransferObjects.RoomsListElement[]>(formatterResolver).Serialize(ref writer, value.List, options);
        }

        public global::Positron.Client.DataTransferObjects.RoomListResponse Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Positron.Client.DataTransferObjects.RoomListResponse();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.List = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.DataTransferObjects.RoomsListElement[]>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class RoomsListElementFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Positron.Client.DataTransferObjects.RoomsListElement>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Positron.Client.DataTransferObjects.RoomsListElement value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(4);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Name, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Uuid, options);
            writer.Write(value.CurrentPlayers);
            writer.Write(value.MaxPlayers);
        }

        public global::Positron.Client.DataTransferObjects.RoomsListElement Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Positron.Client.DataTransferObjects.RoomsListElement();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.Name = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        ____result.Uuid = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.CurrentPlayers = reader.ReadInt32();
                        break;
                    case 3:
                        ____result.MaxPlayers = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name

// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Positron.Client.GameEntities
{
    public sealed class NetGameObjectFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Positron.Client.GameEntities.NetGameObject>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Positron.Client.GameEntities.NetGameObject value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(6);
            writer.Write(value.AssetIndex);
            writer.Write(value.CreationId);
            writer.Write(value.ObjectId);
            writer.Write(value.OwnerClientId);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.Premitive.NetVector3>(formatterResolver).Serialize(ref writer, value.Position, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.Premitive.NetVector3>(formatterResolver).Serialize(ref writer, value.Rotation, options);
        }

        public global::Positron.Client.GameEntities.NetGameObject Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Positron.Client.GameEntities.NetGameObject();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.AssetIndex = reader.ReadUInt64();
                        break;
                    case 1:
                        ____result.CreationId = reader.ReadUInt64();
                        break;
                    case 2:
                        ____result.ObjectId = reader.ReadUInt32();
                        break;
                    case 3:
                        ____result.OwnerClientId = reader.ReadUInt32();
                        break;
                    case 4:
                        ____result.Position = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.Premitive.NetVector3>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 5:
                        ____result.Rotation = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.Premitive.NetVector3>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class NetTransformFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Positron.Client.GameEntities.NetTransform>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Positron.Client.GameEntities.NetTransform value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(3);
            writer.Write(value.ObjectId);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.Premitive.NetVector3>(formatterResolver).Serialize(ref writer, value.Position, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.Premitive.NetVector3>(formatterResolver).Serialize(ref writer, value.Rotation, options);
        }

        public global::Positron.Client.GameEntities.NetTransform Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Positron.Client.GameEntities.NetTransform();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.ObjectId = reader.ReadUInt32();
                        break;
                    case 1:
                        ____result.Position = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.Premitive.NetVector3>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        ____result.Rotation = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Positron.Client.GameEntities.Premitive.NetVector3>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class NetValueFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Positron.Client.GameEntities.NetValue>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Positron.Client.GameEntities.NetValue value, global::MessagePack.MessagePackSerializerOptions options)
        {
            writer.WriteArrayHeader(5);
            writer.Write(value.CreationId);
            writer.Write(value.ParentObjectId);
            writer.Write(value.SubObjectId);
            writer.Write(value.Deleting);
            writer.Write(value.Payload);
        }

        public global::Positron.Client.GameEntities.NetValue Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            var length = reader.ReadArrayHeader();
            var ____result = new global::Positron.Client.GameEntities.NetValue();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.CreationId = reader.ReadUInt64();
                        break;
                    case 1:
                        ____result.ParentObjectId = reader.ReadUInt32();
                        break;
                    case 2:
                        ____result.SubObjectId = reader.ReadUInt16();
                        break;
                    case 3:
                        ____result.Deleting = reader.ReadBoolean();
                        break;
                    case 4:
                        ____result.Payload = global::MessagePack.Internal.CodeGenHelpers.GetArrayFromNullableSequence(reader.ReadBytes());
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

    public sealed class RpcCallFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Positron.Client.GameEntities.RpcCall>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Positron.Client.GameEntities.RpcCall value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(6);
            writer.Write(value.ObjectId);
            writer.Write(value.TargetClientId);
            writer.Write(value.SubObjectId);
            writer.Write(value.Type);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.MethodName, options);
            writer.Write(value.Args);
        }

        public global::Positron.Client.GameEntities.RpcCall Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Positron.Client.GameEntities.RpcCall();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        ____result.ObjectId = reader.ReadUInt32();
                        break;
                    case 1:
                        ____result.TargetClientId = reader.ReadUInt32();
                        break;
                    case 2:
                        ____result.SubObjectId = reader.ReadUInt16();
                        break;
                    case 3:
                        ____result.Type = reader.ReadByte();
                        break;
                    case 4:
                        ____result.MethodName = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 5:
                        ____result.Args = global::MessagePack.Internal.CodeGenHelpers.GetArrayFromNullableSequence(reader.ReadBytes());
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name

// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Positron.Client.GameEntities.Premitive
{
    public sealed class NetVector3Formatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Positron.Client.GameEntities.Premitive.NetVector3>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Positron.Client.GameEntities.Premitive.NetVector3 value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(1);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<float[]>(formatterResolver).Serialize(ref writer, value.Coords, options);
        }

        public global::Positron.Client.GameEntities.Premitive.NetVector3 Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var ____result = new global::Positron.Client.GameEntities.Premitive.NetVector3();

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<float[]>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name

