package authorityschemas

const (
	AUTHORITY_SCHEMA_FILE_NAME = "AuthoritySchema.json"

	PREFAB_SPAWN_ANY  = 0x0
	PREFAB_SPAWN_HOST = 0x1

	PREFAB_DESTROY_ANY   = 0x0
	PREFAB_DESTROY_OWNER = 0x1
	PREFAB_DESTROY_HOST  = 0x2

	PREFAB_OWNERSHIP_TRANSFER_FORBIDDEN = 0x0
	PREFAB_OWNERSHIP_TRANSFER_HOST      = 0x1
	PREFAB_OWNERSHIP_TRANSFER_ANY       = 0x2

	NET_VALUE_OWNER = 0x0
	NET_VALUE_HOST  = 0x1
)
